### ISSUE TITLE
Stopped when already downloading

### ISSUE THREAD

**Issue by inlacou** [txomon/tuenti-downloader#4]
Buenas,

No estaba seguro de si crear un nuevo hilo, pero entiendo que es otro problema. Al tema:

`INFO:root:Downloaded 1638/44900 photos
ERROR:root:Failed but retrying for 0-th time
Traceback (most recent call last):
  File "td.py", line 41, in really_retry
    yield
  File "td.py", line 57, in get_user_album_photos
    res = tsm.Profile_getAlbumPhotos({'page': page, 'pageSize': 1000, 'userId': user})
  File "/usr/local/lib/python2.7/dist-packages/python_tuenti-1.1.0-py2.7.egg/tuenti/tuenti.py", line 90, in request
    ((method, params),), return_request, extra_requests)
  File "/usr/local/lib/python2.7/dist-packages/python_tuenti-1.1.0-py2.7.egg/tuenti/tuenti.py", line 100, in mrequest
    return req.json()
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.1-py2.7.egg/requests/models.py", line 693, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 420, in raw_decode
    raise JSONDecodeError("No JSON object could be decoded", s, idx)
JSONDecodeError: No JSON object could be decoded: line 1 column 0 (char 0)
Traceback (most recent call last):
  File "td.py", line 194, in <module>
    main()
  File "td.py", line 183, in main
    for photo in get_user_album_photos(tsm, user_id):
  File "td.py", line 59, in get_user_album_photos
    res = tsm.Profile_getAlbumPhotos({'page': page, 'pageSize': 1000})
  File "/usr/lib/python2.7/contextlib.py", line 36, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()`

Si sirve de algo, iba por el user 80/204.

Supongo que simplemente se ha encontrado con un caso concreto en el que la api (o el parseo o yo que sé) no ha devuelto un JSON valido y valdría con tener esto en cuenta y pasar al siguiente o lo que sea.

**Comment by txomon** [comment]
Si, de hecho lo había puesto para que si daba un fallo de ese tipo no fallara del tema. Lo de abrir nuevos threads, si ves que el fallo diferente. No pasa nada si realmente es el mismo, se marca como duplicado y listo. Estoy en https://gitter.im/txomon/tuenti-downloader por si quieres hablar mientras vas probando.
